### PR TITLE
COG-1011_COG-1081 View Workers phone number in CWS-CARES

### PR DESCRIPTION
**Pull request by pradipforever**
Added the new phone number information
office_phone_number and phone_extension_number are existing numbers came from Cws Office.
Added new phone_number and phone_extension_number as worker's number and added mock data for UI integration.

### JIRA Issue Link
- [View Workers phone number in CWS-CARES](https://osi-cwds.atlassian.net/browse/COG-1011)

### JIRA Sub Task
- [UserDetails Datamodel Contract Change - mock](https://osi-cwds.atlassian.net/browse/COG-1081)

### Technical Description
Changed the data model in User class and changed mapping logic in groovy mapping.

### Tests
- [ ] I have included unit tests 
- [X] I have included integration tests 
- [ ] I have included performance tests 
- [ ] I have included other tests 
- [ ] I have NOT included tests 

### Types of changes

- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Configuration changes
N/A

### Technical debt
N/A

### Checklist:

- [X] My code is in a stable state ready to be deployable, but not necessarily complete.
- [X] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by sorych** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by sorych** [comment]
retest this please

**Pull request merged**
