### PR TITLE
COG-1082 Worker Phone Number Logic Implementation

### PR DESCRIPTION
**Pull request by dmytro-palczewski-osi**
### JIRA Issue Link
- [COG-108: Worker Phone Number Logic Implementation](https://osi-cwds.atlassian.net/browse/COG-1082)

### Technical Description
Back-end logic to retrieve the actual value of the workers phone number

### Tests
- [x] I have included unit tests 
- [x] I have included integration tests 
- [ ] I have included performance tests 
- [ ] I have included other tests 
- [ ] I have NOT included tests 

### Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [ ] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by sorych** [comment]
retest this please

**Comment by sorych** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
retest this please

**Comment by AVandana-OSI** [comment]
retest this please

**Pull request merged**
