### PR TITLE
COG-179 info rest endpoint to perry

### PR DESCRIPTION
**Pull request by sorych**
### JIRA Issue Link
- [COG-179: info rest endpoint to perry](https://osi-cwds.atlassian.net/browse/COG-179)

### Technical Description

build info rest endpoint to perry

### Tests
- [ ] I have included unit tests 
- [ ] I have included integration tests 
- [ ] I have included performance tests 
- [ ] I have included other tests 
- [ ] I have NOT included tests 

### Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [ ] My code is in a stable state ready to be deployable, but not necessarily complete.
- [ ] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by LeonidMarushevskyi** [comment]
@DmitriyRudenko Why is think system information resource can't be exposed? There is nothing sensitive in information provide by this endpoint.

**Comment by sorych** [comment]
retest this please

**Comment by DmitriyRudenko** [comment]
@LeonidMarushevskyi 

1. Spring scans for all HealthIndicators in entire app and will publish provided info through the health endpoint
1. HealthIndicator is sensitive by its nature and may include such info like disk space, connection settings etc.
3. All CARES API's system-information resources are not exposed to internet, so perry's health endpoint shouldn't be exposed as well
4. In case we if you really want to expose health check to internet then we should make it sensitive=false, and write corresponding integration tests which will validate absence of sensitive info in it.

**Comment by sorych** [comment]
@DmitriyRudenko @LeonidMarushevskyi 

response example:
`{
  "systemInfo": {
    "build": {
      "version": "3.0.3-SNAPSHOT",
      "artifact": "perry",
      "name": "perry",
      "group": "gov.ca.cwds.api",
      "time": "2018-06-06 22:59:15+0000"
    }
  },
  "health": {
    "status": {
      "code": "DOWN",
      "description": ""
    },
    "details": {
      "jwtCheck": {
        "status": {
          "code": "UP",
          "description": ""
        },
        "details": {}
      },
      "cognitoHealthCheck": {
        "status": {
          "code": "DOWN",
          "description": ""
        },
        "details": {
          "error": "com.amazonaws.services.cognitoidp.model.ResourceNotFoundException: User pool us-west-2_iDuUc331Q does not exist. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: e3c4edc0-6a72-11e8-bcfd-c514ab9b1973)"
        }
      },
      "diskSpace": {
        "status": {
          "code": "UP",
          "description": ""
        },
        "details": {
          "total": 33684287488,
          "free": 15729250304,
          "threshold": 10485760
        }
      },
      "redis": {
        "status": {
          "code": "DOWN",
          "description": ""
        },
        "details": {
          "error": "org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool"
        }
      },
      "db": {
        "status": {
          "code": "UP",
          "description": ""
        },
        "details": {
          "dataSource": {
            "status": {
              "code": "UP",
              "description": ""
            },
            "details": {
              "database": "H2",
              "hello": 1
            }
          },
          "tokenDataSource": {
            "status": {
              "code": "UP",
              "description": ""
            },
            "details": {
              "database": "H2",
              "hello": 1
            }
          }
        }
      }
    }
  }
}`

**Comment by DmitriyRudenko** [comment]
That's what I am talking about 🙂

**Comment by sorych** [comment]
image

@DmitriyRudenko docuemntation updated: 

https://osicagov.sharepoint.com/sites/TechnologyPlatformTeam2/_layouts/15/WopiFrame.aspx?sourcedoc=%7BEB8E8C6A-481B-49E3-A855-09DA49CF976B%7D&file=CWDS%20API%20Security%20Developer%27s%20Guide.docx&action=default

**Pull request merged**
