### PR TITLE
CWSUserInfoService refactored

### PR DESCRIPTION
**Pull request by sorych**
### JIRA Issue Link
no Jira ticket for this

### Technical Description

After CwsOffice and StaffPerson Entities have been mapped to UserId through hibernate the CWSUserInfoService method has been refactored to optimize DB calls (not needed DAO calls changed to get methods).

### Tests
- [x] I have included unit tests 
- [x] I have included integration tests 
- [ ] I have included performance tests 
- [ ] I have included other tests 
- [ ] I have NOT included tests 

### Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [ ] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by sorych** [comment]
retest this please

**Comment by sorych** [comment]
retest this please

**Comment by DmitriyRudenko** [comment]
Change UserIdDao: findByIds must return Set(Not List!!) (in order to avoid duplicates)

**Comment by sorych** [comment]
@DmitriyRudenko I will not have duplicates here because I use UserId-StaffPerson-CwsOffice entities chain only and all connections have ManyToOne relations, so it may be always either one or zero existed dependency.

**Comment by sorych** [comment]
@DmitriyRudenko I did testing without annotations and your code works in the same way. One call to the db is a result of strict query with all joins present there. In case you do not specify joins in the query and request UserId those annotations will do the work for you.

**Comment by sorych** [comment]
@DmitriyRudenko updated

**Comment by sorych** [comment]
will be merged in 9.1

**Pull request merged**
