### PR TITLE
HOT-1896: Batch Authorization of clients for Screening HOI Services

### PR DESCRIPTION
**Pull request by SergiiRedchuk**
### JIRA Issue Link
- https://osi-cwds.atlassian.net/browse/HOT-1896

### Technical Description
Changes in ABAC security. Added support for faster authorization of secured objects in collections.

### Tests
- [x] I have included unit tests 

### Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)

### Checklist:
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check Lint/Rubocop, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by DmitriyRudenko** [comment]
Add unit test for authorizer with both filtering and checkInstance or checkId are enabled, make sure in that case batch athorization will be triggered instead of per-instance authrorization

**Comment by DmitriyRudenko** [comment]
plz fix code climate isssues

**Comment by SergiiRedchuk** [comment]
@DmitriyRudenko added tests for fully implemented authorizer with cheks that checkId or checkInstance methods are not called, but filterIds or filterInstances are called in cases of filtering collections,
commit https://github.com/ca-cwds/perry/pull/133/commits/9d9c66e37595ceb0f8ebceb7a8589d45c8f49988

**Comment by SergiiRedchuk** [comment]
@DmitriyRudenko, regarding comment: "filtering functionality should check is param is collection of supported elements and if not - then previous "per-instance" logic should be triggered" - it seems exactly how I implemented that. Please elaborate what you mean.

**Pull request merged**
